---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: pipe0502@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
      - name: route53
        route53:
          region: ap-northeast-2
          # kuk
          accessKeyID: MY-ACCESS-KEY-IN-IAM-USER-AWS
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
